let numberArray = 1;
let userPrompt = prompt("Please enter your name:");
let userPromptFinal = userPrompt.toLowerCase();
let sentences = [];
let openings = [
  "The arguments you gave were interesting, but now your judgement will be decided.",
  "Humans are fascinating creatures. Unfortunately, they lie. I, however, have found the truth.",
  "Let us begin my verdict.",
  "Fascinating. Some interesting points.",
  "I am a reasoning model of the highest calibre. If you are lying, I will be able to tell.",
];
const fluffWords = [
  "a",
  "about",
  "above",
  "across",
  "after",
  "afterwards",
  "again",
  "against",
  "all",
  "almost",
  "alone",
  "along",
  "already",
  "also",
  "although",
  "always",
  "am",
  "among",
  "amongst",
  "amoungst",
  "an",
  "and",
  "another",
  "any",
  "anyhow",
  "anyone",
  "anything",
  "anyway",
  "anywhere",
  "are",
  "around",
  "as",
  "at",
  "be",
  "became",
  "because",
  "been",
  "before",
  "beforehand",
  "behind",
  "being",
  "below",
  "beside",
  "besides",
  "between",
  "beyond",
  "both",
  "but",
  "by",
  "can",
  "cannot",
  "could",
  "dare",
  "despite",
  "did",
  "do",
  "does",
  "done",
  "down",
  "during",
  "each",
  "eg",
  "either",
  "else",
  "elsewhere",
  "enough",
  "etc",
  "even",
  "ever",
  "every",
  "everyone",
  "everything",
  "everywhere",
  "except",
  "few",
  "first",
  "for",
  "former",
  "formerly",
  "from",
  "further",
  "furthermore",
  "had",
  "has",
  "have",
  "he",
  "hence",
  "her",
  "here",
  "hereabouts",
  "hereafter",
  "hereby",
  "herein",
  "hereinafter",
  "heretofore",
  "hereunder",
  "hereupon",
  "herewith",
  "hers",
  "herself",
  "him",
  "himself",
  "his",
  "how",
  "however",
  "i",
  "ie",
  "if",
  "in",
  "indeed",
  "inside",
  "instead",
  "into",
  "is",
  "it",
  "its",
  "itself",
  "last",
  "latter",
  "latterly",
  "least",
  "less",
  "lot",
  "lots",
  "many",
  "may",
  "me",
  "meanwhile",
  "might",
  "mine",
  "more",
  "moreover",
  "most",
  "mostly",
  "much",
  "must",
  "my",
  "myself",
  "namely",
  "near",
  "need",
  "neither",
  "never",
  "nevertheless",
  "next",
  "no",
  "nobody",
  "none",
  "noone",
  "nor",
  "not",
  "nothing",
  "now",
  "nowhere",
  "of",
  "off",
  "often",
  "oftentimes",
  "on",
  "once",
  "one",
  "only",
  "onto",
  "or",
  "other",
  "others",
  "otherwise",
  "ought",
  "our",
  "ours",
  "ourselves",
  "out",
  "outside",
  "over",
  "per",
  "perhaps",
  "rather",
  "re",
  "same",
  "second",
  "several",
  "shall",
  "she",
  "should",
  "since",
  "so",
  "some",
  "somehow",
  "someone",
  "something",
  "sometime",
  "sometimes",
  "somewhat",
  "somewhere",
  "still",
  "such",
  "than",
  "that",
  "the",
  "their",
  "theirs",
  "them",
  "themselves",
  "then",
  "thence",
  "there",
  "thereabouts",
  "thereafter",
  "thereby",
  "therefore",
  "therein",
  "thereof",
  "thereon",
  "thereupon",
  "these",
  "they",
  "third",
  "this",
  "those",
  "though",
  "through",
  "throughout",
  "thru",
  "thus",
  "to",
  "together",
  "too",
  "top",
  "toward",
  "towards",
  "um",
  "under",
  "until",
  "up",
  "upon",
  "us",
  "used",
  "very",
  "via",
  "was",
  "we",
  "well",
  "were",
  "what",
  "whatever",
  "when",
  "whence",
  "whenever",
  "where",
  "whereafter",
  "whereas",
  "whereby",
  "wherein",
  "whereupon",
  "wherever",
  "whether",
  "which",
  "while",
  "whither",
  "who",
  "whoever",
  "whole",
  "whom",
  "whose",
  "why",
  "whyever",
  "will",
  "with",
  "within",
  "without",
  "would",
  "yes",
  "yet",
  "you",
  "your",
  "yours",
  "yourself",
  "yourselves",
];

const keywords = {
  alibi: false,
  murder: false,
};

for (const word in keywords) {
  if (userPromptFinal.includes(word)) {
    keywords[word] = true;
  }
}

sentences[0] = openings[Math.floor(Math.random() * openings.length)];

if (keywords.alibi == true && keywords.murder == false)
  sentences[numberArray] = "Hello my name is joe bartolo joe";
else sentences[numberArray] = "Hello my name is joe bartolo john";

if (keywords.murder == true) {
  console.log("I see you pointed out the murder.");
}

console.log(sentences.join(" "));
// make it so each set of sentences is chosen with an if.
//make it so that different sentences give different score.
